services:
  - type: web
    name: satisfiestech-api
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/satisfiestech.github.io-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: satisfiestech-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: satisfiestech-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: satisfiestech-db
          property: password

databases:
  - name: satisfiestech-db
    databaseName: ecommerce
    user: ecommerce_user