services:
  - type: web
    name: satisfiestech-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d4qr03u3jp1c739mjicg-a.oregon-postgres.render.com:5432/satisfiestech_db
      - key: DATABASE_USERNAME
        value: satisfiestech_db_user
      - key: DATABASE_PASSWORD
        value: dy3onp1dsH0OcK7YTCMWmBQZ3H7LyK1Z
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: SatisfiesTech@2025!Secure
      - key: SERVER_PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://satisfiestech.github.io
      - key: SHOW_SQL
        value: false
